const invoice_data = {
  titles: [
    "Invoice ID",
    "Created",
    "Buyer",
    "Items",
    "State",
    // "Sub Total",
    // "Tax",
    "Grand Total",
    "Payment Status",
    "Delivery Status",
    "Actions",
  ],
  content: [
    {
      invoice_id: 5446546,
      created: 1674461923,
      buyer: {
        name: "Alok Nath",
        email: "alok32@gmail.com",
      },
      items: ["Angaya Podi", "Millet Noodles", "Rasam"],
      destination_state: "Uttar Pradesh",
      //   sub_total: 20512,
      //   tax: 2055,
      grand_total: 25800,
      status: "Booked",
      delivery_status: "Delivered",
    },
    {
      invoice_id: 5446547,
      created: 1684829920,
      buyer: {
        name: "Utkarsh Gupta",
        email: "utGupt@gmail.com",
      },
      items: [
        "Multigrain Atta",
        "Green Gram Dosa Mix",
        "Diabetic Atta",
        "Garlic rasam Powder",
      ],
      destination_state: "Rajasthan",
      //   sub_total: 50124,
      //   tax: 3245,
      grand_total: 55210,
      status: "Paid",
      delivery_status: "Dispatched",
    },
    {
      invoice_id: 5446548,
      created: 1674452572,
      buyer: {
        name: "Priyangshu Das",
        email: "priYangshu20@gmail.com",
      },
      items: ["Multigrain Atta", "Green Gram Dosa Mix", "Diabetic Atta"],
      destination_state: "Kerela",
      //   sub_total: 15963,
      //   tax: 1245,
      grand_total: 20789,
      status: "Cancelled",
      delivery_status: "Cancelled",
    },
    {
      invoice_id: 5446549,
      created: 1674452725,
      buyer: {
        name: "Neetu Kaur",
        email: "neetu54@gmail.com",
      },
      items: [
        "Kokum Rasam Powder ",
        "Garlic rasam Powder",
        "Diabetic Atta",
        "Multigrain Atta",
        "Green Gram Dosa Mix",
      ],
      destination_state: "Assam",
      //   sub_total: 15963,
      //   tax: 5214,
      grand_total: 20789,
      status: "Cancelled",
      delivery_status: "Returned",
    },
    {
      invoice_id: 5446546,
      created: 1674461923,
      buyer: {
        name: "Alok Nath",
        email: "alok32@gmail.com",
      },
      items: ["Angaya Podi", "Millet Noodles", "Rasam"],
      destination_state: "Uttar Pradesh",
      //   sub_total: 20512,
      //   tax: 2055,
      grand_total: 25800,
      status: "Booked",
      delivery_status: "Delivered",
    },
    {
      invoice_id: 5446547,
      created: 1684829920,
      buyer: {
        name: "Utkarsh Gupta",
        email: "utGupt@gmail.com",
      },
      items: [
        "Multigrain Atta",
        "Green Gram Dosa Mix",
        "Diabetic Atta",
        "Garlic rasam Powder",
      ],
      destination_state: "Rajasthan",
      //   sub_total: 50124,
      //   tax: 3245,
      grand_total: 55210,
      status: "Paid",
      delivery_status: "Dispatched",
    },
    {
      invoice_id: 5446548,
      created: 1674452572,
      buyer: {
        name: "Priyangshu Das",
        email: "priYangshu20@gmail.com",
      },
      items: ["Multigrain Atta", "Green Gram Dosa Mix", "Diabetic Atta"],
      destination_state: "Kerela",
      //   sub_total: 15963,
      //   tax: 1245,
      grand_total: 20789,
      status: "Cancelled",
      delivery_status: "Cancelled",
    },
    {
      invoice_id: 5446549,
      created: 1674452725,
      buyer: {
        name: "Neetu Kaur",
        email: "neetu54@gmail.com",
      },
      items: [
        "Kokum Rasam Powder ",
        "Garlic rasam Powder",
        "Diabetic Atta",
        "Multigrain Atta",
        "Green Gram Dosa Mix",
      ],
      destination_state: "Assam",
      //   sub_total: 15963,
      //   tax: 5214,
      grand_total: 20789,
      status: "Cancelled",
      delivery_status: "Returned",
    },
    {
      invoice_id: 5446546,
      created: 1674461923,
      buyer: {
        name: "Alok Nath",
        email: "alok32@gmail.com",
      },
      items: ["Angaya Podi", "Millet Noodles", "Rasam"],
      destination_state: "Uttar Pradesh",
      //   sub_total: 20512,
      //   tax: 2055,
      grand_total: 25800,
      status: "Booked",
      delivery_status: "Delivered",
    },
    {
      invoice_id: 5446547,
      created: 1684829920,
      buyer: {
        name: "Utkarsh Gupta",
        email: "utGupt@gmail.com",
      },
      items: [
        "Multigrain Atta",
        "Green Gram Dosa Mix",
        "Diabetic Atta",
        "Garlic rasam Powder",
      ],
      destination_state: "Rajasthan",
      //   sub_total: 50124,
      //   tax: 3245,
      grand_total: 55210,
      status: "Paid",
      delivery_status: "Dispatched",
    },
    {
      invoice_id: 5446548,
      created: 1674452572,
      buyer: {
        name: "Priyangshu Das",
        email: "priYangshu20@gmail.com",
      },
      items: ["Multigrain Atta", "Green Gram Dosa Mix", "Diabetic Atta"],
      destination_state: "Kerela",
      //   sub_total: 15963,
      //   tax: 1245,
      grand_total: 20789,
      status: "Cancelled",
      delivery_status: "Cancelled",
    },
    {
      invoice_id: 5446549,
      created: 1674452725,
      buyer: {
        name: "Neetu Kaur",
        email: "neetu54@gmail.com",
      },
      items: [
        "Kokum Rasam Powder ",
        "Garlic rasam Powder",
        "Diabetic Atta",
        "Multigrain Atta",
        "Green Gram Dosa Mix",
      ],
      destination_state: "Assam",
      //   sub_total: 15963,
      //   tax: 5214,
      grand_total: 20789,
      status: "Cancelled",
      delivery_status: "Returned",
    },
  ],
  status: [
    {
      name: "Booked",
      color: "#e99f15",
    },
    {
      name: "Paid",
      color: "#00ac69",
    },
    {
      name: "Cancelled",
      color: "#FF0000",
    },
  ],
  delivery_status: [
    {
      name: "Dispatched",
      color: "",
    },
    {
      name: "Delivered",
      color: "#00ac69",
    },
    {
      name: "Cancelled",
      color: "",
    },
    {
      name: "Returned",
      color: "",
    },
  ],
};

export default invoice_data;
